/*
 * ConverterView.java
 */

package converter;

import org.jdesktop.application.Action;
import org.jdesktop.application.SingleFrameApplication;
import org.jdesktop.application.FrameView;
import javax.swing.JDialog;
import javax.swing.JFrame;

/**
 * The application's main frame.
 */
public class ConverterView extends FrameView {

    public ConverterView(SingleFrameApplication app) {
        super(app);

        initComponents();
    }

    @Action
    public void showAboutBox() {
        if (aboutBox == null) {
            JFrame mainFrame = ConverterApp.getApplication().getMainFrame();
            aboutBox = new ConverterAboutBox(mainFrame);
            aboutBox.setLocationRelativeTo(mainFrame);
        }
        ConverterApp.getApplication().show(aboutBox);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        binLabel = new javax.swing.JLabel();
        binField = new javax.swing.JTextField();
        hexField = new javax.swing.JTextField();
        hexLabel = new javax.swing.JLabel();
        decField = new javax.swing.JTextField();
        decLabel = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        javax.swing.JMenu fileMenu = new javax.swing.JMenu();
        resetMenuItem = new javax.swing.JMenuItem();
        javax.swing.JMenuItem exitMenuItem = new javax.swing.JMenuItem();
        javax.swing.JMenu helpMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem aboutMenuItem = new javax.swing.JMenuItem();

        mainPanel.setMaximumSize(new java.awt.Dimension(400, 210));
        mainPanel.setMinimumSize(new java.awt.Dimension(400, 210));
        mainPanel.setName("mainPanel"); // NOI18N
        mainPanel.setOpaque(false);
        mainPanel.setPreferredSize(new java.awt.Dimension(400, 210));

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(converter.ConverterApp.class).getContext().getResourceMap(ConverterView.class);
        binLabel.setText(resourceMap.getString("binLabel.text")); // NOI18N
        binLabel.setName("binLabel"); // NOI18N

        binField.setText(resourceMap.getString("binField.text")); // NOI18N
        binField.setMinimumSize(new java.awt.Dimension(6, 30));
        binField.setName("binField"); // NOI18N
        binField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                binFieldKeyReleased(evt);
            }
        });

        hexField.setMinimumSize(new java.awt.Dimension(6, 30));
        hexField.setName("hexField"); // NOI18N
        hexField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                hexFieldKeyReleased(evt);
            }
        });

        hexLabel.setText(resourceMap.getString("hexLabel.text")); // NOI18N
        hexLabel.setName("hexLabel"); // NOI18N

        decField.setMinimumSize(new java.awt.Dimension(6, 30));
        decField.setName("decField"); // NOI18N
        decField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                decFieldKeyReleased(evt);
            }
        });

        decLabel.setText(resourceMap.getString("decLabel.text")); // NOI18N
        decLabel.setName("decLabel"); // NOI18N

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(binField, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(binLabel)
                    .addComponent(hexLabel)
                    .addComponent(decLabel)
                    .addComponent(hexField, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(decField, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE))
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(binLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(binField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(hexLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hexField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(decLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(decField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        menuBar.setName("menuBar"); // NOI18N

        fileMenu.setText(resourceMap.getString("fileMenu.text")); // NOI18N
        fileMenu.setName("fileMenu"); // NOI18N

        resetMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        resetMenuItem.setText(resourceMap.getString("resetMenuItem.text")); // NOI18N
        resetMenuItem.setName("resetMenuItem"); // NOI18N
        resetMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(resetMenuItem);

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(converter.ConverterApp.class).getContext().getActionMap(ConverterView.class, this);
        exitMenuItem.setAction(actionMap.get("quit")); // NOI18N
        exitMenuItem.setName("exitMenuItem"); // NOI18N
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        helpMenu.setText(resourceMap.getString("helpMenu.text")); // NOI18N
        helpMenu.setName("helpMenu"); // NOI18N

        aboutMenuItem.setAction(actionMap.get("showAboutBox")); // NOI18N
        aboutMenuItem.setName("aboutMenuItem"); // NOI18N
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setComponent(mainPanel);
        setMenuBar(menuBar);
    }// </editor-fold>//GEN-END:initComponents

    private void binFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_binFieldKeyReleased
        String binInput;
        String hexOutput;
        int decOutput = 0;

        binInput = this.binField.getText();
        if (binInput.matches("")) {
            this.decField.setText("");
            hexOutput = "";
        } else {
            decOutput = Integer.parseInt(binInput, 2);
            hexOutput = Integer.toHexString(decOutput);
            this.decField.setText(Integer.toString(decOutput));
        }

        this.hexField.setText(hexOutput);
    }//GEN-LAST:event_binFieldKeyReleased

    private void hexFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hexFieldKeyReleased
        String hexInput;
        String binOutput;
        int decOutput = 0;

        hexInput = this.hexField.getText();
        if (hexInput.matches("")) {
            this.decField.setText("");
            binOutput = "";
        } else {
            decOutput = Integer.parseInt(hexInput, 16);
            binOutput = Integer.toBinaryString(decOutput);
            this.decField.setText(Integer.toString(decOutput));
        }

        this.binField.setText(binOutput);
    }//GEN-LAST:event_hexFieldKeyReleased

    private void decFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_decFieldKeyReleased
        String decInput;
        String hexOutput;
        String binOutput;
        int decNum = 0;

        decInput = this.decField.getText();
        if (decInput.matches("")) {
            hexOutput = "";
            binOutput = "";
        } else {
            decNum = Integer.parseInt(decInput);
            binOutput = Integer.toBinaryString(decNum);
            hexOutput = Integer.toHexString(decNum);
        }
        
        this.hexField.setText(hexOutput.toUpperCase());
        this.binField.setText(binOutput);
    }//GEN-LAST:event_decFieldKeyReleased

    private void resetMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetMenuItemActionPerformed
        this.binField.setText("");
        this.hexField.setText("");
        this.decField.setText("");
    }//GEN-LAST:event_resetMenuItemActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField binField;
    private javax.swing.JLabel binLabel;
    private javax.swing.JTextField decField;
    private javax.swing.JLabel decLabel;
    private javax.swing.JTextField hexField;
    private javax.swing.JLabel hexLabel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem resetMenuItem;
    // End of variables declaration//GEN-END:variables

    private JDialog aboutBox;
    private JDialog errorLog;
}
